require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HikersController do

  # This should return the minimal set of attributes required to create a valid
  # Hiker. As you add validations to Hiker, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HikersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hikers as @hikers" do
      hiker = Hiker.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hikers).should eq([hiker])
    end
  end

  describe "GET show" do
    it "assigns the requested hiker as @hiker" do
      hiker = Hiker.create! valid_attributes
      get :show, {:id => hiker.to_param}, valid_session
      assigns(:hiker).should eq(hiker)
    end
  end

  describe "GET new" do
    it "assigns a new hiker as @hiker" do
      get :new, {}, valid_session
      assigns(:hiker).should be_a_new(Hiker)
    end
  end

  describe "GET edit" do
    it "assigns the requested hiker as @hiker" do
      hiker = Hiker.create! valid_attributes
      get :edit, {:id => hiker.to_param}, valid_session
      assigns(:hiker).should eq(hiker)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hiker" do
        expect {
          post :create, {:hiker => valid_attributes}, valid_session
        }.to change(Hiker, :count).by(1)
      end

      it "assigns a newly created hiker as @hiker" do
        post :create, {:hiker => valid_attributes}, valid_session
        assigns(:hiker).should be_a(Hiker)
        assigns(:hiker).should be_persisted
      end

      it "redirects to the created hiker" do
        post :create, {:hiker => valid_attributes}, valid_session
        response.should redirect_to(Hiker.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hiker as @hiker" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hiker.any_instance.stub(:save).and_return(false)
        post :create, {:hiker => {}}, valid_session
        assigns(:hiker).should be_a_new(Hiker)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hiker.any_instance.stub(:save).and_return(false)
        post :create, {:hiker => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hiker" do
        hiker = Hiker.create! valid_attributes
        # Assuming there are no other hikers in the database, this
        # specifies that the Hiker created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hiker.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hiker.to_param, :hiker => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hiker as @hiker" do
        hiker = Hiker.create! valid_attributes
        put :update, {:id => hiker.to_param, :hiker => valid_attributes}, valid_session
        assigns(:hiker).should eq(hiker)
      end

      it "redirects to the hiker" do
        hiker = Hiker.create! valid_attributes
        put :update, {:id => hiker.to_param, :hiker => valid_attributes}, valid_session
        response.should redirect_to(hiker)
      end
    end

    describe "with invalid params" do
      it "assigns the hiker as @hiker" do
        hiker = Hiker.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hiker.any_instance.stub(:save).and_return(false)
        put :update, {:id => hiker.to_param, :hiker => {}}, valid_session
        assigns(:hiker).should eq(hiker)
      end

      it "re-renders the 'edit' template" do
        hiker = Hiker.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hiker.any_instance.stub(:save).and_return(false)
        put :update, {:id => hiker.to_param, :hiker => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hiker" do
      hiker = Hiker.create! valid_attributes
      expect {
        delete :destroy, {:id => hiker.to_param}, valid_session
      }.to change(Hiker, :count).by(-1)
    end

    it "redirects to the hikers list" do
      hiker = Hiker.create! valid_attributes
      delete :destroy, {:id => hiker.to_param}, valid_session
      response.should redirect_to(hikers_url)
    end
  end

end
