require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MountainsController do

  # This should return the minimal set of attributes required to create a valid
  # Mountain. As you add validations to Mountain, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MountainsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mountains as @mountains" do
      mountain = Mountain.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mountains).should eq([mountain])
    end
  end

  describe "GET show" do
    it "assigns the requested mountain as @mountain" do
      mountain = Mountain.create! valid_attributes
      get :show, {:id => mountain.to_param}, valid_session
      assigns(:mountain).should eq(mountain)
    end
  end

  describe "GET new" do
    it "assigns a new mountain as @mountain" do
      get :new, {}, valid_session
      assigns(:mountain).should be_a_new(Mountain)
    end
  end

  describe "GET edit" do
    it "assigns the requested mountain as @mountain" do
      mountain = Mountain.create! valid_attributes
      get :edit, {:id => mountain.to_param}, valid_session
      assigns(:mountain).should eq(mountain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mountain" do
        expect {
          post :create, {:mountain => valid_attributes}, valid_session
        }.to change(Mountain, :count).by(1)
      end

      it "assigns a newly created mountain as @mountain" do
        post :create, {:mountain => valid_attributes}, valid_session
        assigns(:mountain).should be_a(Mountain)
        assigns(:mountain).should be_persisted
      end

      it "redirects to the created mountain" do
        post :create, {:mountain => valid_attributes}, valid_session
        response.should redirect_to(Mountain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mountain as @mountain" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mountain.any_instance.stub(:save).and_return(false)
        post :create, {:mountain => {}}, valid_session
        assigns(:mountain).should be_a_new(Mountain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mountain.any_instance.stub(:save).and_return(false)
        post :create, {:mountain => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mountain" do
        mountain = Mountain.create! valid_attributes
        # Assuming there are no other mountains in the database, this
        # specifies that the Mountain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mountain.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mountain.to_param, :mountain => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mountain as @mountain" do
        mountain = Mountain.create! valid_attributes
        put :update, {:id => mountain.to_param, :mountain => valid_attributes}, valid_session
        assigns(:mountain).should eq(mountain)
      end

      it "redirects to the mountain" do
        mountain = Mountain.create! valid_attributes
        put :update, {:id => mountain.to_param, :mountain => valid_attributes}, valid_session
        response.should redirect_to(mountain)
      end
    end

    describe "with invalid params" do
      it "assigns the mountain as @mountain" do
        mountain = Mountain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mountain.any_instance.stub(:save).and_return(false)
        put :update, {:id => mountain.to_param, :mountain => {}}, valid_session
        assigns(:mountain).should eq(mountain)
      end

      it "re-renders the 'edit' template" do
        mountain = Mountain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mountain.any_instance.stub(:save).and_return(false)
        put :update, {:id => mountain.to_param, :mountain => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mountain" do
      mountain = Mountain.create! valid_attributes
      expect {
        delete :destroy, {:id => mountain.to_param}, valid_session
      }.to change(Mountain, :count).by(-1)
    end

    it "redirects to the mountains list" do
      mountain = Mountain.create! valid_attributes
      delete :destroy, {:id => mountain.to_param}, valid_session
      response.should redirect_to(mountains_url)
    end
  end

end
